on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout source
         uses: actions/checkout@v2
       - name: Setup node
         uses: actions/setup-node@v2
         with:
          node-version: '12'
       - name: Install dependency packages
         run: npm --prefix ./Server install
       - name: Run server
         run: npm --prefix ./Server start 
       - name: Run test
         run: npm --prefix ./Test run test
         
      #  - name: Run test
      #    uses: actions/npm@master
      #    with:
      #     args: run test