on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout source
         uses: actions/checkout@v2
       - name: Setup node
         uses: actions/setup-node@v2
         with:
          node-version: '12'
       - name: Install dependency packages for Server
         run: npm --prefix ./Server install
       - name: Install dependency packages for Test
         run: npm --prefix ./Test install
       - name: Run server
         run: (npm --prefix ./Server start&)
       - name: Run test
         run: npm --prefix ./Test run test
       - name: Login to GCR
         uses: docker/login-action@v1
         with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
       - name: Build docker image
         uses: docker/build-push-action@v2
         with:
          context: .
          file: ./Server/Dockerfile
          tags: gcr.io/automation-test:${{ steps.get_version.outputs.version }}
          pushed: true
         
      #  - name: Run test
      #    uses: actions/npm@master
      #    with:
      #     args: run test