on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout source
         uses: actions/checkout@v2
       - name: Install dependency packages
         uses: actions/setup-node@v2
         with:
          node-version: '12'
          path: './Server'
         run: npm install
      #  - name: Run test
      #    uses: actions/npm@master
      #    with:
      #     args: run test